- name : installing web server
  hosts : DEV
  become : yes
  tasks :
    - name : installing httpd
      yum :
        name : httpd
        state : latest

    - name : start the httpd
      service :
        name : httpd
        state : started
        enabled : yes