- name : DEMO on stat module
  hosts : DEV
  tasks :
    - name : get the stats of one file
      stat :
        path : /etc/passwd
      register : st

    - name : print the stats
      debug :
        msg : "{{st}}"

    - name : print whether exists or not
      debug :
        msg : "{{st.stat.exists}}"

    - name : run this task when file is exists
      debug : 
        msg : "file is exists"
      when : "st.stat.exists == true"

    - name : run this task when file does not exists
      debug : 
        msg : "file does not exists"
      when : "st.stat.exists == false"