- name : DEMO on find module
  hosts : DEV
  become : yes
  tasks :
    - name : find the *.log files
      find : 
        paths : /demo
        patterns : '*.log'
      register : out

    - name : print the files
      debug :
        msg : "{{out}}"

    - name : remove the files
      file :
        path : "{{item.path}}"
        state : absent
      loop : "{{out.files}}"
        